name = "gleither"
version = "0.1.0"

description = "A small data-structure for representing Left or Right"
licences = ["MIT"]
repository = { type = "github", user = "bwireman", repo = "gleither" }
links = []

# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/. 

[dependencies]
gleam_stdlib = "~> 0.36 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"

[javascript]
typescript_declarations = true
